# GAMEBOARD
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
GAMEBOARD_BACKGROUND = "./Assets/background.jpg"
GAMEBOARD_SOUND = "./Assets/music.mp3"

# MOSQUITO
MOSQUITO_MIN_SIZE = 50
MOSQUITO_MAX_SIZE = 150
MOSQUITO_IMAGE = "./Assets/mosquito.png"
MOSQUITO_SOUND = "./Assets/slap.mp3"

# BEE
BEE_MIN_SIZE = 30
BEE_MAX_SIZE = 180
BEE_IMAGE = "./Assets/bee.png"
BEE_SOUND = "./Assets/au.mp3"
BEE_BACKGROUND_SOUND = "./Assets/bee.mp3"
MINUS_SECOND_FOR_BEE = 10

# STINKY_BUG
STINKY_BUG_MIN_SIZE = 30
STINKY_BUG_MAX_SIZE = 100
STINKY_BUG_IMAGE = "./Assets/bogar.png"
STINKY_BUG_SOUND = "./Assets/nice.mp3"
PLUS_SECOND_FOR_STINKY_BUG = 15

# SCORE BOARD
TIMER_DURATION = 10
FONT_SIZE = 50
RED_COLOR = (255, 0, 0)
WHITE_COLOR = (218, 232, 224)
BLACK_COLOR = (0, 0, 0)
GREEN_COLOR = (18, 219, 98)
HOVER_GREEN_COLOR = (0, 247, 99)
